In [1]:
import numpy as np

In [10]:
a = np.array([0,1,2.6,True,4,5])
print(type(a))     # output: :numpy.ndarray
print(a.dtype)     #output: dtype('int64')
print(a.shape)     #output: (6,)
print(a.ndim)      #output: 1
print(a.size)      #output: 6

<class 'numpy.ndarray'>
float64
(6,)
1
6


In [11]:
b = np.array([20,1,2,3, 4])
print(b)

[20  1  2  3  4]


In [12]:
c = b[1:4]
print(c)

[1 2 3]


In [2]:
arr1 = np.array([1, 2, 3, 4, 5], dtype=int)
arr1

array([1, 2, 3, 4, 5])

In [5]:
arr2 = np.array([10, 20, 30, 40, 50], dtype=float)
arr2

array([10., 20., 30., 40., 50.])

In [7]:
arr3 = np.array(["Hello", "Python"])
arr3

array(['Hello', 'Python'], dtype='<U6')

In [8]:
arr4 = np.array(["Hello", "Python", 1, 2, 3])
arr4

array(['Hello', 'Python', '1', '2', '3'], dtype='<U21')

In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

In [14]:
arr[arr > 5] # type: ignore

array([ 6,  7,  8,  9, 10, 11, 12])

## 2D array

In [24]:
arr5 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr5

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
print(arr5.ndim)
print(arr5.shape)
print(arr5.size)
print(arr5.dtype)
print(arr5.itemsize)
print(arr5.data)
print(type(arr5))

2
(3, 3)
9
int64
8
<class 'numpy.ndarray'>


In [40]:
print(arr5[:,0], '\n-------')
print(arr5[0, :], '\n-------')
print(arr5[-1, :], '\n-------')
print(arr5[:, -1], '\n-------')
print(arr5[-1, -1], '\n-------')
print(arr5[0:2, 0:2], '\n-------')
print(arr5[0:2, :], '\n-------')
print(arr5[:, 0:2], '\n-------')

[1 4 7] 
-------
[1 2 3] 
-------
[7 8 9] 
-------
[3 6 9] 
-------
9 
-------
[[1 2]
 [4 5]] 
-------
[[1 2 3]
 [4 5 6]] 
-------
[[1 2]
 [4 5]
 [7 8]] 
-------


In [21]:
arr6 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arr6

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [22]:
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)
print(arr6.dtype)
print(arr6.itemsize)
print(arr6.data)
print(type(arr6))

2
(3, 4)
12
int64
8
<class 'numpy.ndarray'>


In [42]:
arr6.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [44]:
arr6.flatten(order='A')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [45]:
arr6.flatten(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [46]:
arr6.flatten(order='K')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [47]:
arr6.flatten(order='F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [49]:
arr6.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [50]:
arr6.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [51]:
arr6.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## arranging an array

In [54]:
np.arange(0, 100, 10)   # syntax: min, max, step size

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [55]:
np.arange(0, 100, 2.5)

array([ 0. ,  2.5,  5. ,  7.5, 10. , 12.5, 15. , 17.5, 20. , 22.5, 25. ,
       27.5, 30. , 32.5, 35. , 37.5, 40. , 42.5, 45. , 47.5, 50. , 52.5,
       55. , 57.5, 60. , 62.5, 65. , 67.5, 70. , 72.5, 75. , 77.5, 80. ,
       82.5, 85. , 87.5, 90. , 92.5, 95. , 97.5])

In [57]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
np.zeros_like((5,5))

array([0, 0])

In [62]:
np.ones((5,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [64]:
np.eye(3,3)     # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [67]:
np.random.randint(0, 1000, size=(5,4))

array([[362, 290, 160, 891],
       [479, 300, 180,  39],
       [ 61, 215, 780, 397],
       [558, 323, 289, 748],
       [541, 861, 104, 637]])

In [113]:
firstArray = np.array([[1,2,3], [3,4,5]])
secondArray = np.array([[9,8,7], [20,25,30]])

In [114]:
print(firstArray.shape)
print(secondArray.shape)

(2, 3)
(2, 3)


In [115]:
secondArray + firstArray

array([[10, 10, 10],
       [23, 29, 35]])

In [116]:
secondArray - firstArray

array([[ 8,  6,  4],
       [17, 21, 25]])

In [117]:
secondArray * firstArray

array([[  9,  16,  21],
       [ 60, 100, 150]])

In [118]:
secondArray / firstArray

array([[9.        , 4.        , 2.33333333],
       [6.66666667, 6.25      , 6.        ]])

In [119]:
secondArray ** firstArray

array([[       9,       64,      343],
       [    8000,   390625, 24300000]])

In [121]:
firstArray

array([[1, 2, 3],
       [3, 4, 5]])

In [122]:
secondArray

array([[ 9,  8,  7],
       [20, 25, 30]])

In [120]:
# concatenate
np.concatenate([firstArray, secondArray], axis=0)   # axis=0 - row wise operation

array([[ 1,  2,  3],
       [ 3,  4,  5],
       [ 9,  8,  7],
       [20, 25, 30]])

In [129]:
np.concatenate([firstArray, secondArray], axis=1)   # axis=1 - column wise operation

array([[ 1,  2,  3,  9,  8,  7],
       [ 3,  4,  5, 20, 25, 30]])

## Transpose

In [130]:
firstArray.transpose()

array([[1, 3],
       [2, 4],
       [3, 5]])

In [131]:
firstArray.T

array([[1, 3],
       [2, 4],
       [3, 5]])

In [132]:
np.transpose(firstArray)

array([[1, 3],
       [2, 4],
       [3, 5]])

## https://www.geeksforgeeks.org/numpy-cheat-sheet/